name: safe_map_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^5.0.0

  # Multimedia
  image_picker: ^1.1.0
  crop_your_image: ^0.6.0

  # Mapas y geolocalización
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^9.0.2

  # Firebase (necesario para firebase_options.dart)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9

  # Provider (capa de lógica)
  provider: ^6.0.5

  # Cloudinary - Almacenamiento de imágenes y vídeos
  cloudinary_public: ^0.23.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
